[project]
name = "a004-mpi4py-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mpi4py>=4.0.3",
    "natsort>=8.4.0",
    "numpy>=2.2.4",
]
